{
  "type": "record",
  "name": "ProductReserved",
  "namespace": "warehouse.events",
  "fields": [
    {
      "name": "event_id",
      "type": "string"
    },
    {
      "name": "event_type",
      "type": "string"
    },
    {
      "name": "event_timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "product_id",
      "type": "string"
    },
    {
      "name": "zone_id",
      "type": "string"
    },
    {
      "name": "quantity",
      "type": "int"
    },
    {
      "name": "order_id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
