apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse-movie
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      secure: false
      username: default
      defaultDatabase: default
      dialTimeout: 10
      queryTimeout: 120
      validateSql: false
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
